# Generated by Django 3.1 on 2020-09-16 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('personal_profile', models.TextField()),
                ('image', models.ImageField(upload_to='resume_pics')),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='builder.resume')),
            ],
        ),
        migrations.DeleteModel(
            name='UserPersonalInfo',
        ),
    ]
