# Generated by Django 3.1 on 2020-09-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_auto_20200916_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='from_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='to_date',
            field=models.CharField(max_length=100),
        ),
    ]
