# Generated by Django 3.1 on 2020-09-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_auto_20200917_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skills',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
