# Generated by Django 3.1 on 2020-09-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_auto_20200917_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='from_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='to_date',
            field=models.CharField(max_length=100),
        ),
    ]
